
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Definition of the design system. All colors, gradients, fonts, etc should be defined here. 
All colors MUST be HSL.
*/

@layer base {
  :root {
    --background: 250 100% 98%; /* #f7f7ff */
    --foreground: 0 0% 0%; /* #000000 */

    --card: 250 100% 98%; /* #f7f7ff */
    --card-foreground: 0 0% 0%; /* #000000 */

    --popover: 250 100% 98%; /* #f7f7ff */
    --popover-foreground: 0 0% 0%; /* #000000 */

    --primary: 262 52% 47%; /* #6366f1 - indigo-500 */
    --primary-foreground: 0 0% 100%; /* #ffffff */

    --secondary: 270 91% 65%; /* #a855f7 - purple-500 */
    --secondary-foreground: 0 0% 100%; /* #ffffff */

    --muted: 250 100% 95%; /* #ededff */
    --muted-foreground: 224 71% 4%; /* #0f172a */

    --accent: 275 100% 84%; /* #e879f9 - fuchsia-300 */
    --accent-foreground: 0 0% 0%; /* #000000 */

    --destructive: 0 84% 60%; /* #ef4444 - red-500 */
    --destructive-foreground: 0 0% 100%; /* #ffffff */

    --border: 250 100% 90%; /* #e0e0ff */
    --input: 250 100% 90%; /* #e0e0ff */
    --ring: 262 52% 47%; /* #6366f1 - indigo-500 */

    --radius: 0.5rem;

    --sidebar-background: 250 100% 98%; /* #f7f7ff */
    --sidebar-foreground: 224 71% 4%; /* #0f172a */
    --sidebar-primary: 262 52% 47%; /* #6366f1 - indigo-500 */
    --sidebar-primary-foreground: 0 0% 100%; /* #ffffff */
    --sidebar-accent: 250 100% 95%; /* #ededff */
    --sidebar-accent-foreground: 224 71% 4%; /* #0f172a */
    --sidebar-border: 250 100% 90%; /* #e0e0ff */
    --sidebar-ring: 270 91% 65%; /* #a855f7 - purple-500 */
  }

  .dark {
    --background: 224 71% 4%; /* #0f172a - slate-900 */
    --foreground: 0 0% 100%; /* #ffffff */

    --card: 215 28% 17%; /* #1e293b - slate-800 */
    --card-foreground: 0 0% 100%; /* #ffffff */

    --popover: 215 28% 17%; /* #1e293b - slate-800 */
    --popover-foreground: 0 0% 100%; /* #ffffff */

    --primary: 262 52% 47%; /* #6366f1 - indigo-500 */
    --primary-foreground: 0 0% 100%; /* #ffffff */

    --secondary: 270 91% 65%; /* #a855f7 - purple-500 */
    --secondary-foreground: 0 0% 100%; /* #ffffff */

    --muted: 215 28% 17%; /* #1e293b - slate-800 */
    --muted-foreground: 210 40% 70%; /* #94a3b8 - slate-400 */

    --accent: 275 100% 84%; /* #e879f9 - fuchsia-300 */
    --accent-foreground: 224 71% 4%; /* #0f172a */

    --destructive: 0 84% 60%; /* #ef4444 - red-500 */
    --destructive-foreground: 0 0% 100%; /* #ffffff */

    --border: 215 28% 17%; /* #1e293b - slate-800 */
    --input: 215 28% 17%; /* #1e293b - slate-800 */
    --ring: 262 52% 47%; /* #6366f1 - indigo-500 */
    --sidebar-background: 224 71% 4%; /* #0f172a - slate-900 */
    --sidebar-foreground: 0 0% 100%; /* #ffffff */
    --sidebar-primary: 262 52% 47%; /* #6366f1 - indigo-500 */
    --sidebar-primary-foreground: 0 0% 100%; /* #ffffff */
    --sidebar-accent: 215 28% 17%; /* #1e293b - slate-800 */
    --sidebar-accent-foreground: 0 0% 100%; /* #ffffff */
    --sidebar-border: 215 28% 17%; /* #1e293b - slate-800 */
    --sidebar-ring: 270 91% 65%; /* #a855f7 - purple-500 */
  }

  /* Compact mode styles */
  .compact-mode {
    --spacing-xs: 0.25rem;
    --spacing-sm: 0.5rem;
    --spacing-md: 0.75rem;
    --spacing-lg: 1rem;
    --spacing-xl: 1.5rem;
  }

  .compact-mode .space-y-4 > * + * {
    margin-top: 0.75rem;
  }

  .compact-mode .space-y-6 > * + * {
    margin-top: 1rem;
  }

  .compact-mode .py-8 {
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
  }

  /* No animations mode */
  .no-animations * {
    transition: none !important;
    animation: none !important;
  }
}

@layer base {
  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground;
  }
}
